language: r
cache: packages
warnings_are_errors: true
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
      before_install:
        - R CMD javareconf
    - os: osx
      osx_image: xcode9.2
      before_install:
        - R CMD javareconf
r_packages:
  - covr
r_github_packages:
  - hrbrmstr/pdfboxjars
after_success:
  - R -q -e 'library("covr");codecov()'
